# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyqtdesignerV2.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(921, 710)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_title.setFont(font)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.gridLayout.addWidget(self.label_title, 0, 4, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_2.addWidget(self.progressBar)
        self.pushButton_Run = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Run.setObjectName("pushButton_Run")
        self.horizontalLayout_2.addWidget(self.pushButton_Run)
        self.pushButton_Clear = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Clear.setObjectName("pushButton_Clear")
        self.horizontalLayout_2.addWidget(self.pushButton_Clear)
        self.pushButton_Save = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Save.setEnabled(False)
        self.pushButton_Save.setObjectName("pushButton_Save")
        self.horizontalLayout_2.addWidget(self.pushButton_Save)
        self.gridLayout.addLayout(self.horizontalLayout_2, 5, 4, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 3, 4, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_country = QtWidgets.QLabel(self.centralwidget)
        self.label_country.setObjectName("label_country")
        self.verticalLayout.addWidget(self.label_country)
        self.comboBox_country = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_country.setEnabled(True)
        self.comboBox_country.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_country.setObjectName("comboBox_country")
        self.comboBox_country.addItem("")
        self.comboBox_country.addItem("")
        self.comboBox_country.addItem("")
        self.comboBox_country.addItem("")
        self.comboBox_country.addItem("")
        self.comboBox_country.addItem("")
        self.comboBox_country.addItem("")
        self.comboBox_country.addItem("")
        self.comboBox_country.addItem("")
        self.comboBox_country.addItem("")
        self.verticalLayout.addWidget(self.comboBox_country)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_program = QtWidgets.QLabel(self.centralwidget)
        self.label_program.setObjectName("label_program")
        self.verticalLayout_2.addWidget(self.label_program)
        self.comboBox_program = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_program.setObjectName("comboBox_program")
        self.comboBox_program.addItem("")
        self.comboBox_program.addItem("")
        self.comboBox_program.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_program)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_modheader = QtWidgets.QLabel(self.centralwidget)
        self.label_modheader.setObjectName("label_modheader")
        self.verticalLayout_3.addWidget(self.label_modheader)
        self.comboBox_modheader = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_modheader.setObjectName("comboBox_modheader")
        self.comboBox_modheader.addItem("")
        self.comboBox_modheader.addItem("")
        self.verticalLayout_3.addWidget(self.comboBox_modheader)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 4, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_excel_name = QtWidgets.QLabel(self.centralwidget)
        self.label_excel_name.setObjectName("label_excel_name")
        self.horizontalLayout_3.addWidget(self.label_excel_name)
        self.label_tab_name = QtWidgets.QLabel(self.centralwidget)
        self.label_tab_name.setEnabled(True)
        self.label_tab_name.setObjectName("label_tab_name")
        self.horizontalLayout_3.addWidget(self.label_tab_name)
        self.label_version = QtWidgets.QLabel(self.centralwidget)
        self.label_version.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_version.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_version.setObjectName("label_version")
        self.horizontalLayout_3.addWidget(self.label_version)
        self.gridLayout.addLayout(self.horizontalLayout_3, 6, 4, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 921, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionFAQ = QtWidgets.QAction(MainWindow)
        self.actionFAQ.setObjectName("actionFAQ")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.actionNew.setObjectName("actionNew")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionFAQ)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Solarwinds UAT App"))
        self.label_title.setText(_translate("MainWindow", "UAT Application"))
        self.pushButton_Run.setText(_translate("MainWindow", "Run"))
        self.pushButton_Run.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.pushButton_Clear.setText(_translate("MainWindow", "Clear"))
        self.pushButton_Save.setText(_translate("MainWindow", "Save"))
        self.label_country.setText(_translate("MainWindow", "Country"))
        self.comboBox_country.setItemText(0, _translate("MainWindow", "None"))
        self.comboBox_country.setItemText(1, _translate("MainWindow", "US"))
        self.comboBox_country.setItemText(2, _translate("MainWindow", "DE"))
        self.comboBox_country.setItemText(3, _translate("MainWindow", "FR"))
        self.comboBox_country.setItemText(4, _translate("MainWindow", "ES"))
        self.comboBox_country.setItemText(5, _translate("MainWindow", "IT"))
        self.comboBox_country.setItemText(6, _translate("MainWindow", "CN"))
        self.comboBox_country.setItemText(7, _translate("MainWindow", "PT"))
        self.comboBox_country.setItemText(8, _translate("MainWindow", "RU"))
        self.comboBox_country.setItemText(9, _translate("MainWindow", "JP"))
        self.label_program.setText(_translate("MainWindow", "Program"))
        self.comboBox_program.setItemText(0, _translate("MainWindow", "New Page"))
        self.comboBox_program.setItemText(1, _translate("MainWindow", "Localization"))
        self.comboBox_program.setItemText(2, _translate("MainWindow", "V2 migration"))
        self.label_modheader.setText(_translate("MainWindow", "Mod Header"))
        self.comboBox_modheader.setItemText(0, _translate("MainWindow", "False"))
        self.comboBox_modheader.setItemText(1, _translate("MainWindow", "True"))
        self.label_excel_name.setText(_translate("MainWindow", "Excel file"))
        self.label_tab_name.setText(_translate("MainWindow", "Sheet1"))
        self.label_version.setText(_translate("MainWindow", "V0.3"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save as"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionFAQ.setText(_translate("MainWindow", "FAQ"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

