# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(882, 708)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox_report = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_report.setObjectName("comboBox_report")
        self.comboBox_report.addItem("")
        self.comboBox_report.addItem("")
        self.comboBox_report.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_report)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_Run = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Run.setObjectName("pushButton_Run")
        self.horizontalLayout_2.addWidget(self.pushButton_Run)
        self.pushButton_GoToFolder = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_GoToFolder.setObjectName("pushButton_GoToFolder")
        self.horizontalLayout_2.addWidget(self.pushButton_GoToFolder)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_4.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.gridLayout_4.addWidget(self.label_title, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_dragndrop_image = QtWidgets.QLabel(self.centralwidget)
        self.label_dragndrop_image.setTextFormat(QtCore.Qt.RichText)
        self.label_dragndrop_image.setObjectName("label_dragndrop_image")
        self.gridLayout_4.addWidget(self.label_dragndrop_image, 1, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_4.addWidget(self.progressBar, 2, 0, 1, 1)
        self.label_title.raise_()
        self.label_dragndrop_image.raise_()
        self.progressBar.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 882, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionRun = QtWidgets.QAction(MainWindow)
        self.actionRun.setObjectName("actionRun")
        self.actionGo_To_Folder = QtWidgets.QAction(MainWindow)
        self.actionGo_To_Folder.setObjectName("actionGo_To_Folder")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionFAQ = QtWidgets.QAction(MainWindow)
        self.actionFAQ.setObjectName("actionFAQ")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionRun)
        self.menuFile.addAction(self.actionGo_To_Folder)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionFAQ)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox_report.setItemText(0, _translate("MainWindow", "Select report style"))
        self.comboBox_report.setItemText(1, _translate("MainWindow", "McAllen MRI"))
        self.comboBox_report.setItemText(2, _translate("MainWindow", "More to come..."))
        self.pushButton_Run.setText(_translate("MainWindow", "Run"))
        self.pushButton_GoToFolder.setText(_translate("MainWindow", "Go To Folder"))
        self.label_title.setText(_translate("MainWindow", "Radiology Application"))
        self.label_dragndrop_image.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/DragnDrop/DragnDrop.png\"/></p></body></html>"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionRun.setText(_translate("MainWindow", "Run"))
        self.actionGo_To_Folder.setText(_translate("MainWindow", "Go To Folder"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionFAQ.setText(_translate("MainWindow", "FAQ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

